---
- name: Update apt cache and install dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3
      - python3-venv
      - python3-pip
      - libpq-dev
      - nginx
      - git
    state: present

- name: Create a directory for the Django app
  become: true
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Create a virtual environment
  become: true
  ansible.builtin.command:
    cmd: python3 -m venv {{ venv_dir }}
    creates: "{{ venv_dir }}/bin/activate"

- name: Install Gunicorn
  become: true
  ansible.builtin.pip:
    name: gunicorn
    virtualenv: "{{ venv_dir }}"

- name: Create systemd service for Gunicorn
  become: true
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    mode: '0644'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Disable Default Config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure Nginx
  become: true
  ansible.builtin.template:
    src: nginx_django.j2
    dest: /etc/nginx/sites-available/django
    mode: '0644'

- name: Enable Nginx site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/django
    dest: /etc/nginx/sites-enabled/django
    state: link

- name: Uncomment server_names_hash_bucket_size in nginx configuration
  become: true
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: '^\s*#\s*server_names_hash_bucket_size\s+64;$'
    replace: 'server_names_hash_bucket_size 128;'

- name: Allow NGINX Full
  become: true
  community.general.ufw:
    rule: allow
    name: 'Nginx Full'

- name: Reload NGINX
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
