- name: Playbook for WebApplication
  hosts: node-web
  become: true
  roles:
    - apt
    - django

- name: Playbook for Databases
  hosts: node-db
  become: true
  roles:
    - apt
    - nginx
    - mysql
    - api
