##############################
#  Configure API
##############################

- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Edit Nginx default conf
  become: true
  ansible.builtin.template:
    src: morelessapi_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default
    force: true
    owner: root
    group: root
    mode: '0644'

- name: Create /var/www/api
  become: true
  ansible.builtin.file:
    path: /var/www/api
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

##############################
#   Install ufw
##############################

- name: Install ufw
  become: true
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH connections on port 22
  become: true
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    comment: 'Allow SSH'

- name: Allow MySQL connections on port 3306
  become: true
  community.general.ufw:
    rule: allow
    port: '3306'
    proto: tcp
    comment: 'Allow MySQL'

- name: Allow HTTP connections on port 80
  become: true
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: 'Allow Web for API'

- name: Enable firewall ufw
  become: true
  community.general.ufw:
    state: enabled
    policy: allow
