- name: Install Depedencies
  ansible.builtin.apt:
    name:
      - wget
      - tar
    state: present
    update_cache: true

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.8.0.linux-amd64.tar.gz
    mode: '0755'
    owner: root
    group: root

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-1.8.0.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    creates: /usr/local/bin/node_exporter-1.8.0.linux-amd64

- name: Move Node Exporter binary to /usr/local/bin
  ansible.builtin.command: mv /usr/local/bin/node_exporter-1.8.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    creates: /usr/local/bin/node_exporter

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /sbin/nologin

- name: Create systemd service file for Node Exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0755'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started

- name: Clean up downloaded and extracted files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/node_exporter-1.8.0.linux-amd64.tar.gz
    - /usr/local/bin/node_exporter-1.8.0.linux-amd64
