- name: Install required packages
  ansible.builtin.apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
    state: present

- name: Create keyrings directory for Grafana GPG key
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: "0755"

- name: Remove existing Grafana GPG key if it exists
  ansible.builtin.file:
    path: "/etc/apt/keyrings/grafana.gpg"
    state: absent

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: "https://apt.grafana.com/gpg.key"
    dest: "/etc/apt/keyrings/grafana.gpg"
    mode: "0644"

- name: Add Grafana GPG key to the keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/trusted.gpg.d/grafana.gpg /etc/apt/keyrings/grafana.gpg
  changed_when: false

- name: Add Grafana repository with signed-by
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/grafana.gpg] https://apt.grafana.com stable main"
    state: present
    filename: "grafana"

- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Start Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true

- name: Ensure Nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Create Nginx configuration for Grafana
  ansible.builtin.template:
    src: "grafana.conf.j2"
    dest: "/etc/nginx/sites-available/grafana.conf"
    mode: "0644"
  notify: Restart Nginx

- name: Ensure the Grafana Nginx configuration is enabled
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/grafana.conf"
    dest: "/etc/nginx/sites-enabled/grafana.conf"
    state: link
  notify: Restart Nginx

- name: Ensure backup directory exists
  ansible.builtin.file:
    path: "/var/lib/grafana/backup"
    state: directory
    owner: grafana
    group: grafana
    mode: "0755"

- name: Create backup script for Grafana database
  ansible.builtin.template:
    src: "grafana_backup_script.j2"
    dest: "/var/lib/grafana/backup/backup_grafana_db.sh"
    owner: grafana
    group: grafana
    mode: "0755"

- name: Create RESTORE script for Grafana database
  ansible.builtin.template:
    src: "grafana_restore_script.j2"
    dest: "/var/lib/grafana/backup/restore_grafana_db.sh"
    owner: grafana
    group: grafana
    mode: "0755"
