##############################
#   Install MySQL Server
##############################
- name: Install MySQL Server
  become: true
  ansible.builtin.apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pip
    state: present
    update_cache: true

######################################
# INSTALL MYSQL DEPENDENCIES
######################################

- name: Ensure PyMySQL is installed
  become: true
  ansible.builtin.pip:
    name: PyMySQL
    state: present

##############################
#   Ensure MySQL is Running
##############################
- name: Ensure MySQL is running and starts on boot
  become: true
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Update MySQL password for superuser `{{ mysql_superuser }}`
  become: true
  community.mysql.mysql_user:
    name: "{{ mysql_superuser }}"
    host: localhost
    password: "{{ mysql_superuser_password }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: ""
    login_port: "{{ mysql_port }}"
    login_host: localhost
    login_unix_socket: "{{ mysql_socket }}"
    check_implicit_admin: true

- name: Add user to access "moreless" database
  become: true
  community.mysql.mysql_user:
    name: "{{ mysql_moreless_user }}"
    host: localhost
    password: "{{ mysql_moreless_password }}"
    priv: "moreless.*:ALL"
    login_user: "{{ mysql_superuser }}"
    login_password: "{{ mysql_superuser_password }}"
    login_port: "{{ mysql_port }}"
    login_host: localhost
    login_unix_socket: "{{ mysql_socket }}"
    check_implicit_admin: true

- name: Create system-wide MySQL configuration file
  become: true
  ansible.builtin.template:
    src: system_wide_mysql.cnf.j2
    dest: /etc/my.cnf
    mode: '0644'

- name: Create MySQL configuration file for `{{ mysql_superuser }}`
  become: true
  ansible.builtin.template:
    src: root.my.cnf.j2
    dest: "{{ mysql_superuser_home }}/.my.cnf"
    mode: '0600'
  notify:
    - Restart MySQL

##############################
# Handlers
##############################
- name: Restart MySQL
  become: true
  ansible.builtin.service:
    name: mysql
    state: restarted
