- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    
- name: Ensure pip is installed
  yum:
    name: python3-pip
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install ansible-lint using pip
  pip:
    name: ansible-lint
    state: present