- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure pip is installed
  ansible.builtin.yum:
    name: python3-pip
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install ansible-lint using pip
  ansible.builtin.pip:
    name: ansible-lint
    state: present
