---
galaxy_info:
  author: LoDy
  description: Maven Agent
  company: N/A
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
dependencies: []
